#ifndef _KBD_H
#define _KBD_H

#include <Ecore_X.h>

typedef enum {
    KEYBOARD_OFF = ECORE_X_VIRTUAL_KEYBOARD_STATE_OFF,
    KEYBOARD_PIN = ECORE_X_VIRTUAL_KEYBOARD_STATE_PIN,
    KEYBOARD_ALPHA = ECORE_X_VIRTUAL_KEYBOARD_STATE_ALPHA,
    KEYBOARD_NUMERIC = ECORE_X_VIRTUAL_KEYBOARD_STATE_NUMERIC
} KeyboardMode;

void kbd_show(KeyboardMode);
void kbd_hide();

#endif
