/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS
#define DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_GSM_SMS_get_service_bearer (DBusGProxy *proxy, char ** OUT_mode, GError **error)

{
  return dbus_g_proxy_call (proxy, "GetServiceBearer", error, G_TYPE_INVALID, G_TYPE_STRING, OUT_mode, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_GSM_SMS_get_service_bearer_reply) (DBusGProxy *proxy, char * OUT_mode, GError *error, gpointer userdata);

static void
org_freesmartphone_GSM_SMS_get_service_bearer_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  char * OUT_mode;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_STRING, &OUT_mode, G_TYPE_INVALID);
  (*(org_freesmartphone_GSM_SMS_get_service_bearer_reply)data->cb) (proxy, OUT_mode, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_GSM_SMS_get_service_bearer_async (DBusGProxy *proxy, org_freesmartphone_GSM_SMS_get_service_bearer_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "GetServiceBearer", org_freesmartphone_GSM_SMS_get_service_bearer_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_GSM_SMS_set_service_bearer (DBusGProxy *proxy, const char * IN_mode, GError **error)

{
  return dbus_g_proxy_call (proxy, "SetServiceBearer", error, G_TYPE_STRING, IN_mode, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_GSM_SMS_set_service_bearer_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_freesmartphone_GSM_SMS_set_service_bearer_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_freesmartphone_GSM_SMS_set_service_bearer_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_GSM_SMS_set_service_bearer_async (DBusGProxy *proxy, const char * IN_mode, org_freesmartphone_GSM_SMS_set_service_bearer_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SetServiceBearer", org_freesmartphone_GSM_SMS_set_service_bearer_async_callback, stuff, g_free, G_TYPE_STRING, IN_mode, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_freesmartphone_GSM_SMS_send_message (DBusGProxy *proxy, const char * IN_recipient_number, const char * IN_contents, const gboolean IN_want_report, gint* OUT_transaction_index, GError **error)

{
  return dbus_g_proxy_call (proxy, "SendMessage", error, G_TYPE_STRING, IN_recipient_number, G_TYPE_STRING, IN_contents, G_TYPE_BOOLEAN, IN_want_report, G_TYPE_INVALID, G_TYPE_INT, OUT_transaction_index, G_TYPE_INVALID);
}

typedef void (*org_freesmartphone_GSM_SMS_send_message_reply) (DBusGProxy *proxy, gint OUT_transaction_index, GError *error, gpointer userdata);

static void
org_freesmartphone_GSM_SMS_send_message_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_transaction_index;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_transaction_index, G_TYPE_INVALID);
  (*(org_freesmartphone_GSM_SMS_send_message_reply)data->cb) (proxy, OUT_transaction_index, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_freesmartphone_GSM_SMS_send_message_async (DBusGProxy *proxy, const char * IN_recipient_number, const char * IN_contents, const gboolean IN_want_report, org_freesmartphone_GSM_SMS_send_message_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "SendMessage", org_freesmartphone_GSM_SMS_send_message_async_callback, stuff, g_free, G_TYPE_STRING, IN_recipient_number, G_TYPE_STRING, IN_contents, G_TYPE_BOOLEAN, IN_want_report, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_freesmartphone_GSM_SMS */

G_END_DECLS
